### ISSUE TITLE
improve: titleやnameの別ファイルでの定義

### ISSUE THREAD

**Issue by kanakanho** [kajiLabTeam/ipsj-national-convention-typst-template#6]
## 起きていること

タイトルや著者の情報を`main.typ`の中に記述している

## 望む状態

yml ファイルに定義して、main.typに直接読み込むと便利なのではないか？
別になくても困らない

`bib.yml`
```yml
title:
  - Typst を用いた
    論文のテンプレート
name:
  - ja: "佐藤智"
    en: "Satoru Sato"
    group: 1
  - ja: "斎藤彩都"
    en: "Saito Saito"
    group: 2
  - ja: "山田邪馬"
    en: "Yamada Yama"
    group: 1
affiliations:
  - ja: "愛知工業大学情報科学部"
    en: "Aichi Institute of Technology"
    group: 1
  - ja: "愛知工業大学大学院経営情報科学研究科"
    en: "Department of Information Science"
    group: 2
```

`main.typ`
```typ
#let bib = yaml("bib.yml")

#show: template.with(
  title: bib.title,
  names: bib.name,
  affiliations: bib.affiliations,
)
```
